### ISSUE TITLE
请问教师网络的模型在哪里下载呢?

### ISSUE THREAD

**Issue by JinYu1998** [yufanLIU/CrossArch_KD#2]

**Comment by yufanLIU** [comment]
code里面的教师网络就是pytorch自带的预训练模型，自动就会下载的

**Comment by JinYu1998** [comment]
> code里面的教师网络就是pytorch自带的预训练模型，自动就会下载的

不好意思, 我可能没有描述清楚我的问题.

我指的是哪里可以获取到论文中所使用模型在**Cifar-100**上的权重.

**Comment by yufanLIU** [comment]
论文中使用了公司的商用baseline模型作为教师网络，但这些教师模型很遗憾无法公开。因此，在GitHub中，我们提供的是pytorch官方的baseline教师网络和增强方法。该复现结果相对于学生模型baseline的提升是与论文中差不多的(GitHub首页中也有展示)。
