### ISSUE TITLE
Is there a version of this code for CIFAR100？

### ISSUE THREAD

**Issue by SunkiLin** [yufanLIU/CrossArch_KD#3]
**hi ！thanks for your great work！**
I noticed that you ran your code on CIFAR100 in your essay, but I can only find the ImageNet version in your open source code. How can I run your code on CIFAR100?
:) @yufanLIU

**Comment by Malaika68** [comment]
@SunkiLin Hello, did you manage to run code with ImageNet and was it successful?

**Comment by SunkiLin** [comment]
> @SunkiLin Hello, did you manage to run code with ImageNet and was it successful?
I'd like to do it, but I don't have enough compute resources to run resnet50 on ImageNet (the experimental configuration for this paper).

**Comment by Malaika68** [comment]
> > @SunkiLin Hello, did you manage to run code with ImageNet and was it successful?
> > I'd like to do it, but I don't have enough compute resources to run resnet50 on ImageNet (the experimental configuration for this paper).

Thanks for the reply :)

**Comment by Malaika68** [comment]
@SunkiLin Do you know if they are using the original ImageNet with millions of images or ImageNet mini for training?
